import { createHash } from "node:crypto";
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const outputDirectory = path.join(projectRoot, "dist");
const supported =
  /\.(?:html|js|css|json|webmanifest|svg|png|webp|jpe?g|gif|ico|woff2?|ttf|mp3|ogg|wav|m4a|wasm)$/i;
const budget = 24 * 1024 * 1024;

async function collect(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const file = path.join(directory, entry.name);
      if (entry.isDirectory()) return collect(file);
      if (
        !entry.isFile() ||
        !supported.test(entry.name) ||
        entry.name === "sw.js"
      )
        return [];
      // Preserve source PNGs for provenance; mobile clients use the optimized WebP.
      if (
        directory === path.join(outputDirectory, "assets") &&
        ["coqui-coach.png", "football-preview.png"].includes(entry.name)
      )
        return [];
      return [file];
    }),
  );
  return files.flat().sort();
}

const files = await collect(outputDirectory);
for (const required of ["index.html", "offline.html", "manifest.webmanifest"]) {
  if (!files.includes(path.join(outputDirectory, required)))
    throw new Error(
      `Offline build is missing ${required}. Run vite build first.`,
    );
}
let total = 0;
const digest = createHash("sha256");
digest.update(await readFile(fileURLToPath(import.meta.url)));
const urls = [];
for (const file of files) {
  const relative = path
    .relative(outputDirectory, file)
    .split(path.sep)
    .join("/");
  const bytes = await readFile(file);
  total += (await stat(file)).size;
  digest.update(relative).update("\0").update(bytes).update("\0");
  // Pages redirects HTML filenames; cache their canonical URLs so navigation
  // never receives a redirected response from the service worker.
  urls.push(
    relative === "index.html"
      ? "/"
      : relative === "offline.html"
        ? "/offline"
        : "/" + relative.split("/").map(encodeURIComponent).join("/"),
  );
}
if (total > budget)
  throw new Error(
    `Offline assets exceed the 24 MiB limit (${(total / 1048576).toFixed(1)} MiB). Optimize core assets before release.`,
  );
const version = digest.digest("hex").slice(0, 16);

const worker = `/* Generated by scripts/create-sw.mjs. Do not edit dist/sw.js. */
const VERSION = ${JSON.stringify(version)};
const PREFIX = 'coqui-kickoff-static-';
const CACHE = PREFIX + VERSION;
const PRECACHE = ${JSON.stringify(urls)};
const ASSETS = new Set(PRECACHE);

self.addEventListener('install', event => {
  // A new version waits until all old app windows close. Never reload a lesson.
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(PREFIX) && name !== CACHE).map(name => caches.delete(name)));
    await self.clients.claim();
    const windows = await self.clients.matchAll({ type: 'window' });
    windows.forEach(client => client.postMessage({ type: 'COQUI_OFFLINE_READY', version: VERSION }));
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'COQUI_CACHE_STATUS') {
    event.waitUntil(caches.has(CACHE).then(ready => {
      if (ready) event.source?.postMessage({ type: 'COQUI_OFFLINE_READY', version: VERSION });
    }));
  }
});

async function withRange(response, request) {
  const range = request.headers.get('range');
  if (!range) return response;
  // iOS audio playback requests byte ranges even for local, cached recordings.
  const bytes = await response.arrayBuffer();
  const match = /^bytes=(\\d*)-(\\d*)$/.exec(range);
  if (!match || (!match[1] && !match[2])) return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + bytes.byteLength } });
  const start = match[1] ? Number(match[1]) : Math.max(0, bytes.byteLength - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(Number(match[2]), bytes.byteLength - 1) : bytes.byteLength - 1;
  if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end || start >= bytes.byteLength) return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + bytes.byteLength } });
  const headers = new Headers(response.headers);
  headers.set('Content-Range', 'bytes ' + start + '-' + end + '/' + bytes.byteLength);
  headers.set('Content-Length', String(end - start + 1));
  headers.set('Accept-Ranges', 'bytes');
  return new Response(bytes.slice(start, end + 1), { status: 206, headers });
}

self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    // Serve one coherent app version, including all its lazy game/audio chunks.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      return await cache.match('/') || await fetch(request).catch(async () =>
        await cache.match('/offline') || new Response('Open Coquí Kickoff online once to save it for offline practice.', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }));
    })());
    return;
  }
  if (!ASSETS.has(url.pathname)) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(url.pathname);
    if (cached) return withRange(cached, request);
    return fetch(request);
  })());
});
`;

await writeFile(path.join(outputDirectory, "sw.js"), worker, "utf8");
console.log(
  `Offline worker ${version}: ${urls.length} core assets, ${(total / 1048576).toFixed(2)} MiB. Optional videos stay online-only.`,
);
